export const PERFIS = {
  DIRECAO: "DIRECAO",
  COORDENACAO: "COORDENACAO",
  AEE: "AEE",
  MEDIADOR: "MEDIADOR",
  ASSISTENTE: "ASSISTENTE",
  REGENTE: "REGENTE",
  ATENDIMENTO_DOMICILIAR: "ATENDIMENTO_DOMICILIAR",
};

export const PERFIS_COM_ACESSO_INSTITUCIONAL = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
];

export const PERFIS_COM_LEITURA_ALUNOS_VINCULADOS = [
  PERFIS.MEDIADOR,
  PERFIS.ASSISTENTE,
  PERFIS.REGENTE,
  PERFIS.ATENDIMENTO_DOMICILIAR,
];

export const PERFIS_APOIO_ACOMPANHAMENTO = [PERFIS.MEDIADOR, PERFIS.ASSISTENTE];

export const PERFIS_SISTEMA = [
  ...PERFIS_COM_ACESSO_INSTITUCIONAL,
  ...PERFIS_COM_LEITURA_ALUNOS_VINCULADOS,
];

export const PERFIS_MODULO_ALUNOS = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
  PERFIS.REGENTE,
  PERFIS.MEDIADOR,
  PERFIS.ASSISTENTE,
  PERFIS.ATENDIMENTO_DOMICILIAR,
];

export const PERFIS_MODULO_SONDAGEM = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
];

export const PERFIS_MODULO_HABILIDADES = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
  PERFIS.REGENTE,
];

export const PERFIS_MODULO_ACOMPANHAMENTO = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
  PERFIS.REGENTE,
  PERFIS.MEDIADOR,
  PERFIS.ASSISTENTE,
  PERFIS.ATENDIMENTO_DOMICILIAR,
];

export const PERFIS_MODULO_MONITORAMENTO = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
];

export const PERFIS_MODULO_RELATORIOS = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
  PERFIS.REGENTE,
  PERFIS.ATENDIMENTO_DOMICILIAR,
];

export const PERFIS_MODULO_PAINEL_COORDENACAO = [
  PERFIS.DIRECAO,
  PERFIS.COORDENACAO,
  PERFIS.AEE,
];

export const PERFIL_LABEL = {
  DIRECAO: "Direção",
  COORDENACAO: "Coordenação",
  AEE: "Professora do AEE",
  MEDIADOR: "Mediador",
  ASSISTENTE: "Assistente Educacional",
  REGENTE: "Professor Regente",
  ATENDIMENTO_DOMICILIAR: "Atendimento Domiciliar",
};
